---
title: "Example"
author: "Nathaniel Price"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```




```{r, warning = FALSE}
library(tvdiff)
library(tidyr)
library(dplyr)
library(ggplot2)

# Load demo data
data("smalldemodata")

# Build dataframe
smallEx <-
  smalldemodata %>%
  # Estimate derivative
  mutate(dxdt =
           TVRegDiffR(
             data = obs,
             iter = 1e3,
             alph = 0.2,
             scale = "small",
             ep = 1e-6,
             dx = 0.01
           )[-1]) %>% 
  # Simple numerical integration
  mutate(dx = lead(x) - x,
         pred = obs[1] + cumsum(dxdt*dx),
         true = abs(x - 0.5)) %>% 
  # Collect in long form
  gather(key, value, -x, -dx)

# Plot observed vs predicted
ggplot(smallEx %>% 
         filter(key != "dxdt"), 
       aes(x = x, y = value, color = key, linetype = key)) +
  geom_line(size = 1.1)

# Plot derivative
ggplot(smallEx %>% 
         filter(key == "dxdt"), 
       aes(x = x, y = value)) +
  geom_point()

```

```{r}

# Load data
data("largedemodata")

# Build dataframe
largeEx <-
  largedemodata %>%
  slice(seq(1, n(), 1e2)) %>% 
  # Estimate derivative
  mutate(dxdt =
           TVRegDiffR(
             data = obs,
             iter = 40L,
             alph = 1e3,
             scale = "large",
             ep = 1e-6,
             dx = 100
           )) %>% 
  # Simple numerical integration
  mutate(dx = lead(x) - x,
         pred = obs[1] + cumsum(dxdt*dx)) %>% 
  # Collect in long form
  gather(key, value, -x, -dx)

# Plot observed vs predicted
ggplot(largeEx %>% 
         filter(key != "dxdt"), 
       aes(x = x, y = value, color = key, linetype = key)) +
  geom_line(size = 1.2)

# Plot derivative
ggplot(largeEx %>% 
         filter(key == "dxdt"), 
       aes(x = x, y = value)) +
  geom_point()


```

```{r}

# Load data
data("paleo")

# Linear interpolate data 
xout <- seq(min(paleo$sortVar), max(paleo$sortVar), length.out = 700)
paleoInterp <- 
  paleo %>%
  select(-cellID, -site) %>% 
  rename(t = sortVar, y = value) %>% 
  group_by(variable) %>% 
  nest() %>% 
  mutate(
    t = purrr::map(data, ~ approx(.$t, .$y, xout = xout)$x, rule = 1),
    y = purrr::map(data, ~ approx(.$t, .$y, xout = xout)$y, rule = 1)
  ) %>%
  dplyr::select(-data) %>%
  unnest()

# Calculate distance
paleoDistance <- 
  paleoInterp %>% 
  group_by(variable) %>% 
  mutate(dy = lead(y) - y,
         dt = lead(t) - t) %>% 
  group_by(t) %>% 
  summarize(ds = sqrt(sum(dy^2))) %>% 
  mutate(s = cumsum(ds)) %>% 
  select(-ds) %>% 
  na.omit()
  

# Build dataframe
paleoEx <-
  paleoDistance %>% 
  mutate(dt = lead(t) - t) %>% 
  # Estimate derivative
  mutate(dsdt =
           TVRegDiffR(
             data = s,
             iter = 2e3,
             alph = 100,
             scale = "small",
             ep = 1e-6,
             dx = dt[1]
           )[-1]) %>% 
  # Simple numerical integration
  mutate(pred = s[1] + cumsum(dsdt*dt)) %>% 
  # Collect in long form
  gather(key, value, -t, -dt)

# Plot observed vs predicted
ggplot(paleoEx %>% 
         filter(key %in% c("s", "pred")), 
       aes(x = t, y = value, color = key, linetype = key)) +
  geom_line(size = 1.2) +
  labs(x = "time",
       y = "cummulative change in state")

# Plot derivative
ggplot(paleoEx %>% 
         filter(key == "dsdt"), 
       aes(x = t, y = value)) +
  geom_point() +
  labs(x = "time", 
       y = "rate of change")


```


